@startuml pc1
set separator none
title GeoCientifica - Containers

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<GeoCientifica.ADMPROYECTOSGEOLÓGICOS>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam hexagon<<GeoCientifica.APIGATEWAY>> {
  BackgroundColor #ff8000
  FontColor #ffffff
  BorderColor #b25900
  shadowing false
}
skinparam rectangle<<GeoCientifica.APPWEB>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<BI>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
  shadowing false
}
skinparam rectangle<<GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam hexagon<<CLOUDS3>> {
  BackgroundColor #ff8000
  FontColor #ffffff
  BorderColor #b25900
  shadowing false
}
skinparam rectangle<<GeoCientifica.GETSIONMUESTRAS>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<GeoCientifica.INFOMUESTRAS>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<LABORATORIO>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
  shadowing false
}
skinparam database<<GeoCientifica.ORACLE>> {
  BackgroundColor #ec0e0e
  FontColor #ffffff
  BorderColor #a50909
  shadowing false
}
skinparam hexagon<<GeoCientifica.RECURSOSCLOUD>> {
  BackgroundColor #ff8000
  FontColor #ffffff
  BorderColor #b25900
  shadowing false
}
skinparam rectangle<<REPOSITORIOINGEMMET>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
  shadowing false
}
skinparam rectangle<<GeoCientifica.SISTEMASDEARCHIVOS>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2e6295
  roundCorner 20
  shadowing false
}
skinparam rectangle<<TRAMITEADMINISTRATIVO>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
  shadowing false
}
skinparam person<<Usuario>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
  shadowing false
}
skinparam rectangle<<VULCANOLOGIA>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
  roundCorner 20
  shadowing false
}
skinparam rectangle<<GeoCientifica>> {
  BorderColor #1a9032
  FontColor #1a9032
  shadowing false
}

person "==Usuario\n<size:10>[Person]</size>\n\nDescripción de usuarios" <<Usuario>> as Usuario
rectangle "==TRAMITE ADMINISTRATIVO\n<size:10>[Software System]</size>\n\nInternal System" <<TRAMITEADMINISTRATIVO>> as TRAMITEADMINISTRATIVO
rectangle "==LABORATORIO\n<size:10>[Software System]</size>\n\nInternal System" <<LABORATORIO>> as LABORATORIO
rectangle "==VULCANOLOGIA\n<size:10>[Software System]</size>\n\nInternal System" <<VULCANOLOGIA>> as VULCANOLOGIA
rectangle "==BI\n<size:10>[Software System]</size>\n\nInternal System" <<BI>> as BI
rectangle "==REPOSITORIO INGEMMET\n<size:10>[Software System]</size>\n\nInternal System" <<REPOSITORIOINGEMMET>> as REPOSITORIOINGEMMET
hexagon "==CLOUD S3\n<size:10>[Software System]</size>" <<CLOUDS3>> as CLOUDS3

rectangle "GeoCientifica\n<size:10>[Software System]</size>" <<GeoCientifica>> {
  rectangle "==SISTEMAS DE ARCHIVOS\n<size:10>[Container]</size>\n\nSystem Software" <<GeoCientifica.SISTEMASDEARCHIVOS>> as GeoCientifica.SISTEMASDEARCHIVOS
  rectangle "==ADM PROYECTOS GEOLÓGICOS\n<size:10>[Container]</size>\n\nJBOSS JSON" <<GeoCientifica.ADMPROYECTOSGEOLÓGICOS>> as GeoCientifica.ADMPROYECTOSGEOLÓGICOS
  rectangle "==APP WEB\n<size:10>[Container: JBOSS JSON]</size>\n\nApp Web" <<GeoCientifica.APPWEB>> as GeoCientifica.APPWEB
  hexagon "==APIGATEWAY\n<size:10>[Container: Java]</size>\n\nApI Gateway" <<GeoCientifica.APIGATEWAY>> as GeoCientifica.APIGATEWAY
  hexagon "==RECURSOS CLOUD\n<size:10>[Container: PYTHON]</size>\n\nJakarta" <<GeoCientifica.RECURSOSCLOUD>> as GeoCientifica.RECURSOSCLOUD
  database "==ORACLE\n<size:10>[Container: ORACLE 19C]</size>\n\nBase de datos" <<GeoCientifica.ORACLE>> as GeoCientifica.ORACLE
  rectangle "==INFO MUESTRAS\n<size:10>[Container]</size>\n\nJBOSS JSON" <<GeoCientifica.INFOMUESTRAS>> as GeoCientifica.INFOMUESTRAS
  rectangle "==GETSION MUESTRAS\n<size:10>[Container]</size>\n\nJBOSS JSON" <<GeoCientifica.GETSIONMUESTRAS>> as GeoCientifica.GETSIONMUESTRAS
  rectangle "==CATALOGO DE RECURSOS GEOLÓGICOS\n<size:10>[Container]</size>\n\nJBOSS JSON" <<GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS>> as GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS
}

GeoCientifica.APIGATEWAY .[#707070,thickness=2].> GeoCientifica.RECURSOSCLOUD : "<color:#707070>USA"
GeoCientifica.RECURSOSCLOUD .[#707070,thickness=2].> CLOUDS3 : "<color:#707070>usa"
GeoCientifica.RECURSOSCLOUD .[#707070,thickness=2].> GeoCientifica.SISTEMASDEARCHIVOS : "<color:#707070>usa"
GeoCientifica.RECURSOSCLOUD .[#707070,thickness=2].> GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS : "<color:#707070>usa"
GeoCientifica.INFOMUESTRAS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>usa"
GeoCientifica.GETSIONMUESTRAS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>usa"
GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>usa"
GeoCientifica.ADMPROYECTOSGEOLÓGICOS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>usa"
Usuario .[#707070,thickness=2].> GeoCientifica.APPWEB : "<color:#707070>usa"
GeoCientifica.APPWEB .[#707070,thickness=2].> GeoCientifica.INFOMUESTRAS : "<color:#707070>usa"
GeoCientifica.APPWEB .[#707070,thickness=2].> GeoCientifica.GETSIONMUESTRAS : "<color:#707070>usa"
GeoCientifica.APPWEB .[#707070,thickness=2].> GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS : "<color:#707070>usa"
GeoCientifica.APPWEB .[#707070,thickness=2].> GeoCientifica.ADMPROYECTOSGEOLÓGICOS : "<color:#707070>usa"
GeoCientifica.INFOMUESTRAS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>lee y escribe"
GeoCientifica.GETSIONMUESTRAS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>lee y escribe"
GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>lee y escribe"
GeoCientifica.ADMPROYECTOSGEOLÓGICOS .[#707070,thickness=2].> GeoCientifica.ORACLE : "<color:#707070>lee y escribe"
GeoCientifica.APPWEB .[#707070,thickness=2].> GeoCientifica.APIGATEWAY : "<color:#707070>autoriza"
GeoCientifica.CATALOGODERECURSOSGEOLÓGICOS .[#707070,thickness=2].> GeoCientifica.SISTEMASDEARCHIVOS : "<color:#707070>lee y escribe"
GeoCientifica.ADMPROYECTOSGEOLÓGICOS .[#707070,thickness=2].> TRAMITEADMINISTRATIVO : "<color:#707070>usa"
GeoCientifica.ADMPROYECTOSGEOLÓGICOS .[#707070,thickness=2].> LABORATORIO : "<color:#707070>usa"
GeoCientifica.ADMPROYECTOSGEOLÓGICOS .[#707070,thickness=2].> VULCANOLOGIA : "<color:#707070>usa"
GeoCientifica.ADMPROYECTOSGEOLÓGICOS .[#707070,thickness=2].> BI : "<color:#707070>usa"
GeoCientifica.ADMPROYECTOSGEOLÓGICOS .[#707070,thickness=2].> REPOSITORIOINGEMMET : "<color:#707070>usa"
GeoCientifica.RECURSOSCLOUD .[#707070,thickness=2].> GeoCientifica.ADMPROYECTOSGEOLÓGICOS : "<color:#707070>usa"
@enduml
